FROM node:24 as builder
WORKDIR /app
COPY ./app/package*.json ./
RUN npm install


FROM node:24-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY ./app/index.js ./
EXPOSE 3000
CMD ["npm", "start"]